version: '3.7'

services:
  #######
  # DFS #
  #######
  namenode:
    image: sapdas/hadoop-namenode:2.10.2
    container_name: namenode
    hostname: namenode
    platform: linux/amd64
    networks:
      - hadoop
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    env_file:
      - ./hadoop.env

  datanode1:
    image: sapdas/hadoop-datanode:2.10.2
    container_name: datanode1
    hostname: datanode1
    platform: linux/amd64
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    ports:
      - "50075:50075"
    env_file:
      - ./hadoop.env

  ########
  # YARN #
  ########

  resourcemanager:
    image: sapdas/hadoop-resourcemanager:2.10.2
    container_name: resourcemanager
    hostname: resourcemanager
    platform: linux/amd64
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075"
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: sapdas/hadoop-nodemanager:2.10.2
    container_name: nodemanager1
    hostname: nodemanager1
    platform: linux/amd64
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 resourcemanager:8088"
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env

  historyserver:
    image: sapdas/hadoop-historyserver:2.10.2
    container_name: historyserver
    hostname: historyserver
    platform: linux/amd64
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 resourcemanager:8088"
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env
  
  ########
  # HIVE #
  ########

  hive-metastore-postgresql:
    image: sapdas/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    hostname: hive-metastore-postgresql
    platform: linux/amd64
    networks:
      - hadoop
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  hive-metastore:
    image: sapdas/hive:2.3.2
    platform: linux/amd64
    container_name: hive-metastore
    hostname: hive-metastore
    networks:
      - hadoop
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  hive-server:
    image: sapdas/hive:2.3.2
    platform: linux/amd64
    container_name: hive-server
    hostname: hive-server
    networks:
      - hadoop
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  hadoop:
    name: hadoop
